import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const Map<String, Map<String, String>> _translations = {
    'ar': {
      'app_name': 'RIM WAY',
      'finding_driver': 'جارِ البحث عن سائق...',
      'driver_assigned': 'السائق في الطريق إليك',
      'driver_arrived': 'لقد وصل السائق. يرجى التوجه إليه.',
      'in_progress': 'الرحلة جارية',
      'no_driver_found': 'لا يوجد سائقون متاحون حالياً. يرجى المحاولة لاحقاً.',
      'cancel': 'إلغاء',
      'home': 'الرئيسية',
      'rides': 'الرحلات',
      'favorites': 'المفضلة',
      'profile': 'حسابي',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'welcome_back': 'مرحباً بك في RIM WAY',
      'enter_phone': 'أدخل رقم هاتفك',
      'phone_hint': 'مثال: 40000000',
      'send_otp': 'إرسال رمز التحقق',
      'invalid_phone': 'رقم الهاتف غير صالح',
      'enter_otp': 'أدخل رمز التحقق (4 أرقام)',
      'verify_otp': 'تأكيد',
      'invalid_otp': 'رمز التحقق غير صحيح',
      'logout': 'تسجيل الخروج',
      'no_incoming_rides': 'لا توجد طلبات جديدة',
      'captain_accept_ride': 'قبول الرحلة',
      'captain_arrive': 'وصلت إلى نقطة الانطلاق',
      'captain_passenger_boarded': 'الراكب ركب معي',
      'captain_start_ride': 'ابدأ الرحلة',
      'captain_complete_ride': 'إنهاء الرحلة',
      'ride_no_longer_available': 'الرحلة لم تعد متاحة',
      'ride_action_failed': 'فشل الإجراء',
      'final_fare_unavailable': 'السعر النهائي غير متاح',
      'ride_already_taken': 'الرحلة تم قبولها مسبقاً',

      // Ride flow
      'where_to': 'إلى أين؟',
      'request_ride_subtitle': 'أدخل وجهتك لطلب رحلة',
      'pickup_location': 'موقع الانطلاق',
      'enter_destination': 'أدخل الوجهة',
      'estimate_ride': 'تقدير السعر',
      'request_ride': 'طلب رحلة',
      'requesting': 'جارِ الطلب...',
      'estimated_fare': 'السعر المقدر',
      'minutes': 'دقيقة',
      'change_destination': 'تغيير الوجهة',
      'searching_subtitle': 'يرجى الانتظار، نبحث عن أقرب سائق',
      'driver_on_the_way': 'السائق في طريقه إليك',
      'please_meet_driver': 'يرجى التوجه إلى موقع السائق',
      'heading_to_destination': 'في الطريق إلى وجهتك',
      'ride_completed': 'اكتملت الرحلة ✓',
      'done': 'تم',
      'try_again': 'إعادة المحاولة',
      'ride_cancelled': 'تم إلغاء الرحلة',
      'ok': 'حسناً',
      'unknown_error': 'حدث خطأ غير متوقع',
      'resend_otp': 'إعادة إرسال الرمز',
      'resend_in': 'إعادة الإرسال بعد',
      'seconds': 'ثانية',
      'otp_sent_to': 'تم إرسال رمز التحقق إلى',
      'change_phone': 'تغيير الرقم',
      'rate_driver': 'تقييم السائق',
      'rate_ride_prompt': 'كيف كانت تجربتك في هذه الرحلة؟',
      'optional_comment': 'أضف تعليقاً (اختياري)',
      'submit_rating': 'إرسال التقييم',
      'rating_submitted': 'شكراً لتقييمك!',
      'select_service': 'اختر نوع الخدمة',
      'current_location': 'موقعي الحالي',
      'confirm_pickup': 'تحديد الانطلاق من هنا',
      'confirm_dropoff': 'تحديد الوجهة هنا',
      'mru': 'أوقية',
      'distance': 'المسافة',
      'km': 'كم',
      'cancel_ride_confirm': 'هل أنت متأكد من إلغاء الرحلة؟',
      'yes_cancel': 'نعم، إلغاء الرحلة',
      'no_keep': 'لا، متابعة الرحلة',

      // Captain Registration Flow
      'start': 'ابدأ',
      'captain_portal': 'بوابة الكباتن',
      'join_captains': 'انضم إلى كباتن RIM WAY',
      'join_captains_subtitle': 'حقق دخلاً إضافياً بحرية وأمان وكن مدير نفسك',
      'select_country': 'الدولة',
      'terms_agreement': 'أوافق على اللوائح والقوانين وشروط الاستخدام',
      'continue_btn': 'استمرار',
      'change_language': 'تغيير اللغة',
      'status_pending_review': 'طلبك قيد المراجعة',
      'pending_review_msg': 'يقوم فريق إدارة RIM WAY بمراجعة وثائقك ومعلومات مركبتك بدقة. ستصلك الموافقة فور اكتمال التدقيق لتتمكن من بدء العمل.',
      'check_status': 'تحديث حالة الطلب',
      'status_rejected': 'لم تتم الموافقة على الطلب',
      'rejection_reason_label': 'سبب الرفض من الإدارة',
      'edit_and_resubmit': 'تعديل البيانات وإعادة الإرسال',
      'status_suspended': 'الحساب موقوف',
      'suspended_msg': 'تم إيقاف حسابك من قبل الإدارة. يرجى التواصل مع الدعم الفني لمزيد من المعلومات.',
      'personal_info': 'البيانات الشخصية',
      'full_name': 'الاسم الكامل',
      'full_name_hint': 'أدخل اسمك الكامل كما في بطاقة الهوية',
      'phone_number': 'رقم الهاتف',
      'profile_photo': 'الصورة الشخصية',
      'upload_photo': 'رفع صورة',
      'take_photo': 'التقاط صورة',
      'choose_gallery': 'من المعرض',
      'required_documents': 'وثائق الكابتن المطلوبة',
      'national_id': 'بطاقة التعريف الوطنية',
      'driving_license': 'رخصة السياقة (إلزامية)',
      'vehicle_insurance': 'وثيقة التأمين للمركبة',
      'vehicle_registration': 'البطاقة الرمادية / تسجيل المركبة (إلزامية)',
      'upload_document': 'رفع الوثيقة',
      'document_uploaded': 'تم الرفع ✓',
      'vehicle_info': 'بيانات المركبة',
      'brand': 'ماركة السيارة',
      'brand_hint': 'مثال: تويوتا (Toyota)',
      'model': 'موديل السيارة',
      'model_hint': 'مثال: كورولا (Corolla)',
      'year': 'سنة الصنع',
      'color': 'لون السيارة',
      'color_hint': 'مثال: أبيض',
      'plate_number': 'رقم اللوحة',
      'plate_number_hint': 'مثال: 1234AA00',
      'service_type': 'نوع الخدمة',
      'select_service_type': 'اختر نوع الخدمة',
      'vehicle_photos': 'صور المركبة الأربع المطلوبة',
      'vehicle_front': 'صورة السيارة من الأمام',
      'vehicle_back': 'صورة السيارة من الخلف',
      'vehicle_right': 'صورة السيارة من اليمين',
      'vehicle_left': 'صورة السيارة من اليسار',
      'review_summary': 'مراجعة وتأكيد طلب التسجيل',
      'submit_application': 'إرسال طلب التسجيل',
      'submitting': 'جارِ إرسال الطلب...',
      'complete': 'مكتمل ✓',
      'missing': 'مطلوب *',
      'mandatory_field_missing': 'يرجى إكمال كافة الحقول والوثائق والصور الإلزامية قبل المتابعة',
      'submission_success': 'تم إرسال طلبك بنجاح للمراجعة الإدارية',
      'step_personal': 'الشخصية',
      'step_vehicle': 'المركبة',
      'step_documents': 'الوثائق',
      'step_photos': 'صور السيارة',
      'step_review': 'المراجعة',
      'login_as_passenger': 'تسجيل الدخول كراكب',
      'login_as_captain': 'تسجيل الدخول / الانضمام ككابتن',
      'wallet': 'المحفظة والرصيد',
      'statistics': 'الإحصائيات',
      'history': 'سجل الرحلات',
      'delete_account': 'حذف الحساب',
      'operating_balance': 'الرصيد التشغيلي',
      'top_up_wallet': 'شحن المحفظة',
      'contact_whatsapp_topup': 'تواصل مع خدمة الشحن عبر واتساب',
      'wallet_exhausted_warning': 'تنبيه: رصيدك التشغيلي نافد (0 MRU أو سالب). لن تتمكن من استقبال أي رحلات جديدة حتى تقوم بشحن محفظتك.',
      'wallet_active_status': 'المحفظة مفعلة - يمكنك استقبال الرحلات',
      'wallet_how_it_works': 'يدفع الزبون 100% من سعر الرحلة نقداً في يدك مباشرة. ريم واي لا تستلم أجرة الرحلة، بل تخصم فقط عمولتها من رصيدك التشغيلي المسبق.',
      'recent_transactions': 'سجل الحركات المالية',
      'no_transactions': 'لا توجد حركات مالية مسجلة',
      'commission_debit': 'خصم عمولة المنصة',
      'top_up_credit': 'شحن رصيد معتمد',
      'manual_credit': 'إيداع إداري',
      'manual_debit': 'خصم إداري',
      'top_up_dialog_title': 'طلب شحن الرصيد التشغيلي',
      'top_up_dialog_desc': 'يمكنك التواصل مباشرة عبر واتساب مع خدمة شحن ريم واي، أو إرسال تفاصيل التحويل البنكي:',
      'transfer_amount': 'مبلغ الشحن (MRU)',
      'transfer_reference': 'رقم الإشعار / المرجع (اختياري)',
      'submit_request': 'إرسال الطلب',
      'open_whatsapp': 'فتح محادثة واتساب',
      'top_up_submitted_success': 'تم إرسال طلب الشحن بنجاح وهو بانتظار اعتماد الإدارة',
    },
    'fr': {
      'app_name': 'RIM WAY',
      'finding_driver': 'Recherche d\'un chauffeur...',
      'driver_assigned': 'Le chauffeur est en route',
      'driver_arrived': 'Le chauffeur est arrivé.',
      'in_progress': 'Course en cours',
      'no_driver_found': 'Aucun chauffeur disponible pour le moment. Veuillez réessayer.',
      'cancel': 'Annuler',
      'home': 'Accueil',
      'rides': 'Courses',
      'favorites': 'Favoris',
      'profile': 'Profil',
      'settings': 'Paramètres',
      'language': 'Langue',
      'welcome_back': 'Bienvenue sur RIM WAY',
      'enter_phone': 'Entrez votre numéro',
      'phone_hint': 'Ex: 40000000',
      'send_otp': 'Envoyer le code',
      'invalid_phone': 'Numéro invalide',
      'enter_otp': 'Entrez le code (4 chiffres)',
      'verify_otp': 'Vérifier',
      'invalid_otp': 'Code invalide',
      'logout': 'Se déconnecter',
      'no_incoming_rides': 'Aucune nouvelle demande',
      'captain_accept_ride': 'Accepter la course',
      'captain_arrive': 'Arrivé au point de départ',
      'captain_passenger_boarded': 'Passager à bord',
      'captain_start_ride': 'Démarrer la course',
      'captain_complete_ride': 'Terminer la course',
      'ride_no_longer_available': 'Course plus disponible',
      'ride_action_failed': 'L\'action a échoué',
      'final_fare_unavailable': 'Prix final indisponible',
      'ride_already_taken': 'La course est déjà prise',

      // Ride flow
      'where_to': 'Où allez-vous?',
      'request_ride_subtitle': 'Entrez votre destination pour commander',
      'pickup_location': 'Point de départ',
      'enter_destination': 'Entrez la destination',
      'estimate_ride': 'Estimer le prix',
      'request_ride': 'Commander',
      'requesting': 'En cours...',
      'estimated_fare': 'Prix estimé',
      'minutes': 'min',
      'change_destination': 'Changer destination',
      'searching_subtitle': 'Nous recherchons le chauffeur le plus proche',
      'driver_on_the_way': 'Le chauffeur est en route',
      'please_meet_driver': 'Rejoignez le chauffeur',
      'heading_to_destination': 'En route vers la destination',
      'ride_completed': 'Course terminée ✓',
      'done': 'OK',
      'try_again': 'Réessayer',
      'ride_cancelled': 'Course annulée',
      'ok': 'OK',
      'unknown_error': 'Erreur inattendue',
      'resend_otp': 'Renvoyer le code',
      'resend_in': 'Renvoyer dans',
      'seconds': 'secondes',
      'otp_sent_to': 'Code envoyé au',
      'change_phone': 'Modifier le numéro',
      'rate_driver': 'Évaluer le chauffeur',
      'rate_ride_prompt': 'Comment s\'est passée votre course ?',
      'optional_comment': 'Commentaire (optionnel)',
      'submit_rating': 'Envoyer l\'évaluation',
      'rating_submitted': 'Merci pour votre évaluation !',
      'select_service': 'Choisir la catégorie',
      'current_location': 'Ma position actuelle',
      'confirm_pickup': 'Départ ici',
      'confirm_dropoff': 'Destination ici',
      'mru': 'MRU',
      'distance': 'Distance',
      'km': 'km',
      'cancel_ride_confirm': 'Êtes-vous sûr de vouloir annuler ?',
      'yes_cancel': 'Oui, annuler',
      'no_keep': 'Non, continuer',

      // Captain Registration Flow
      'start': 'Commencer',
      'captain_portal': 'Portail Chauffeur',
      'join_captains': 'Rejoignez les chauffeurs RIM WAY',
      'join_captains_subtitle': 'Gagnez un revenu supplémentaire en toute liberté et sécurité',
      'select_country': 'Pays',
      'terms_agreement': 'J\'accepte les règlements, les lois et les conditions d\'utilisation',
      'continue_btn': 'Continuer',
      'change_language': 'Changer de langue',
      'status_pending_review': 'Votre demande est en cours d\'examen',
      'pending_review_msg': 'L\'équipe de gestion de RIM WAY examine attentivement vos documents et les informations de votre véhicule. Vous recevrez l\'approbation dès que la vérification sera terminée pour commencer votre activité.',
      'check_status': 'Actualiser le statut',
      'status_rejected': 'Demande d\'inscription refusée',
      'rejection_reason_label': 'Motif du refus par l\'administration',
      'edit_and_resubmit': 'Modifier les données et renvoyer',
      'status_suspended': 'Compte suspendu',
      'suspended_msg': 'Votre compte a été suspendu par l\'administration. Veuillez contacter le support pour plus d\'informations.',
      'personal_info': 'Informations personnelles',
      'full_name': 'Nom complet',
      'full_name_hint': 'Entrez votre nom complet selon votre pièce d\'identité',
      'phone_number': 'Numéro de téléphone',
      'profile_photo': 'Photo de profil',
      'upload_photo': 'Télécharger une photo',
      'take_photo': 'Prendre une photo',
      'choose_gallery': 'Depuis la galerie',
      'required_documents': 'Documents requis du chauffeur',
      'national_id': 'Carte Nationale d\'Identité',
      'driving_license': 'Permis de conduire (obligatoire)',
      'vehicle_insurance': 'Attestation d\'assurance du véhicule',
      'vehicle_registration': 'Carte Grise / Immatriculation (obligatoire)',
      'upload_document': 'Télécharger le document',
      'document_uploaded': 'Téléchargé ✓',
      'vehicle_info': 'Informations sur le véhicule',
      'brand': 'Marque du véhicule',
      'brand_hint': 'Ex: Toyota',
      'model': 'Modèle du véhicule',
      'model_hint': 'Ex: Corolla',
      'year': 'Année de fabrication',
      'color': 'Couleur du véhicule',
      'color_hint': 'Ex: Blanc',
      'plate_number': 'Numéro d\'immatriculation',
      'plate_number_hint': 'Ex: 1234AA00',
      'service_type': 'Catégorie de service',
      'select_service_type': 'Sélectionnez une catégorie',
      'vehicle_photos': '4 Photos requises du véhicule',
      'vehicle_front': 'Photo du véhicule de face',
      'vehicle_back': 'Photo du véhicule de dos',
      'vehicle_right': 'Photo du véhicule côté droit',
      'vehicle_left': 'Photo du véhicule côté gauche',
      'review_summary': 'Vérification de la demande avant envoi',
      'submit_application': 'Soumettre la demande d\'inscription',
      'submitting': 'Envoi de la demande en cours...',
      'complete': 'Complet ✓',
      'missing': 'Requis *',
      'mandatory_field_missing': 'Veuillez compléter tous les champs, documents et photos obligatoires avant de continuer',
      'submission_success': 'Votre demande a été envoyée avec succès pour examen administratif',
      'step_personal': 'Personnel',
      'step_vehicle': 'Véhicule',
      'step_documents': 'Documents',
      'step_photos': 'Photos',
      'step_review': 'Récapitulatif',
      'login_as_passenger': 'Connexion Passager',
      'login_as_captain': 'Connexion / Inscription Chauffeur',
      'wallet': 'Portefeuille & Solde',
      'statistics': 'Statistiques',
      'history': 'Historique des courses',
      'delete_account': 'Supprimer le compte',
      'operating_balance': 'Solde opérationnel',
      'top_up_wallet': 'Recharger le portefeuille',
      'contact_whatsapp_topup': 'Contacter le service de recharge via WhatsApp',
      'wallet_exhausted_warning': 'Attention : Votre solde opérationnel est épuisé (0 MRU ou négatif). Vous ne pouvez recevoir aucune course avant de recharger votre portefeuille.',
      'wallet_active_status': 'Portefeuille actif - Votre solde permet de recevoir des courses',
      'wallet_how_it_works': 'Le passager vous paie 100% du prix de la course en espèces directement. RIM WAY ne prend pas l\'argent de la course, mais déduit uniquement sa commission de votre solde opérationnel préfinancé.',
      'recent_transactions': 'Historique des transactions',
      'no_transactions': 'Aucune transaction enregistrée',
      'commission_debit': 'Déduction commission plateforme',
      'top_up_credit': 'Recharge de solde approuvée',
      'manual_credit': 'Crédit administratif',
      'manual_debit': 'Débit administratif',
      'top_up_dialog_title': 'Demande de recharge de solde',
      'top_up_dialog_desc': 'Contactez directement le service client via WhatsApp ou soumettez votre référence de virement :',
      'transfer_amount': 'Montant de recharge (MRU)',
      'transfer_reference': 'Référence du virement (optionnel)',
      'submit_request': 'Envoyer la demande',
      'open_whatsapp': 'Ouvrir WhatsApp',
      'top_up_submitted_success': 'Demande de recharge soumise avec succès, en attente de validation',
    },
    'en': {
      'app_name': 'RIM WAY',
      'finding_driver': 'Finding a driver...',
      'driver_assigned': 'Driver is on the way',
      'driver_arrived': 'Driver has arrived. Please meet them.',
      'in_progress': 'Ride active',
      'no_driver_found': 'No drivers available right now. Please try again.',
      'cancel': 'Cancel',
      'home': 'Home',
      'rides': 'Rides',
      'favorites': 'Favorites',
      'profile': 'Profile',
      'settings': 'Settings',
      'language': 'Language',
      'welcome_back': 'Welcome to RIM WAY',
      'enter_phone': 'Enter your phone number',
      'phone_hint': 'Ex: 40000000',
      'send_otp': 'Send Verification Code',
      'invalid_phone': 'Invalid phone number',
      'enter_otp': 'Enter verification code (4 digits)',
      'verify_otp': 'Verify',
      'invalid_otp': 'Invalid verification code',
      'logout': 'Logout',
      'no_incoming_rides': 'No incoming rides',
      'captain_accept_ride': 'ACCEPT RIDE',
      'captain_arrive': 'ARRIVED AT PICKUP',
      'captain_passenger_boarded': 'PASSENGER BOARDED',
      'captain_start_ride': 'START RIDE',
      'captain_complete_ride': 'COMPLETE RIDE',
      'ride_no_longer_available': 'Ride is no longer available',
      'ride_action_failed': 'Action failed',
      'final_fare_unavailable': 'Final fare unavailable',
      'ride_already_taken': 'Ride already taken',

      // Ride flow
      'where_to': 'Where to?',
      'request_ride_subtitle': 'Enter your destination to request a ride',
      'pickup_location': 'Pickup location',
      'enter_destination': 'Enter destination',
      'estimate_ride': 'Estimate Fare',
      'request_ride': 'Request Ride',
      'requesting': 'Requesting...',
      'estimated_fare': 'Estimated fare',
      'minutes': 'min',
      'change_destination': 'Change destination',
      'searching_subtitle': 'Please wait while we find the nearest driver',
      'driver_on_the_way': 'Driver is on the way',
      'please_meet_driver': 'Please meet the driver at the pickup',
      'heading_to_destination': 'Heading to your destination',
      'ride_completed': 'Ride Completed ✓',
      'done': 'Done',
      'try_again': 'Try Again',
      'ride_cancelled': 'Ride Cancelled',
      'ok': 'OK',
      'unknown_error': 'An unexpected error occurred',
      'resend_otp': 'Resend Code',
      'resend_in': 'Resend in',
      'seconds': 'seconds',
      'otp_sent_to': 'Verification code sent to',
      'change_phone': 'Change number',
      'rate_driver': 'Rate Driver',
      'rate_ride_prompt': 'How was your ride?',
      'optional_comment': 'Optional comment',
      'submit_rating': 'Submit Rating',
      'rating_submitted': 'Thank you for your rating!',
      'select_service': 'Select Service Type',
      'current_location': 'Current Location',
      'confirm_pickup': 'Set Pickup Here',
      'confirm_dropoff': 'Set Destination Here',
      'mru': 'MRU',
      'distance': 'Distance',
      'km': 'km',
      'cancel_ride_confirm': 'Are you sure you want to cancel the ride?',
      'yes_cancel': 'Yes, Cancel Ride',
      'no_keep': 'No, Keep Ride',
    }
  };

  String translate(String key) {
    return _translations[locale.languageCode]?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['ar', 'fr', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}

extension AppLocalizationsContext on BuildContext {
  String tr(String key) => AppLocalizations.of(this)?.translate(key) ?? key;
}
